ALTER TABLE transaction
  DROP FOREIGN KEY `FK7FA0D2DE2E76915B`, 
  DROP FOREIGN KEY `FK7FA0D2DE374A3CCF`;

ALTER TABLE transaction 
  ADD COLUMN `pair_id` INT(11) NULL DEFAULT NULL, 
  ADD COLUMN `transfer` BIT(1) NOT NULL DEFAULT 0, 
  CHANGE COLUMN `common` `common` BIT(1) NOT NULL DEFAULT 0, 
  CHANGE COLUMN `timestmp` `timestmp` DATETIME NOT NULL, 
  CHANGE COLUMN `account_id` `account_id` INT(11) NOT NULL, 
  CHANGE COLUMN `actor_id` `actor_id` INT(11) NOT NULL, 
  ADD CONSTRAINT `FK7FA0D2DE2E76915B` FOREIGN KEY (`actor_id`) REFERENCES `user`(`id`), 
  ADD CONSTRAINT `FK7FA0D2DE374A3CCF` FOREIGN KEY (`account_id`) REFERENCES `account` (`id`),
  ADD CONSTRAINT `FK_TRANSACT_PAIR` FOREIGN KEY (`pair_id`) REFERENCES `transaction` (`id`) 
    ON DELETE CASCADE ON UPDATE RESTRICT, 
  ADD INDEX `FK_TRANSACT_PAIR` (`pair_id` ASC);

ALTER TABLE `account`
  ADD COLUMN `owner_id` INT(11) NULL DEFAULT NULL, 
  ADD COLUMN `public` BIT(1) NOT NULL DEFAULT 1,
  ADD CONSTRAINT `FK_ACCOUNT_OWNER` FOREIGN KEY (`owner_id`) REFERENCES `user` (`id`)
    ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD INDEX `FK_ACCOUNT_OWNER` (`owner_id` ASC);

drop table `personallimit`;
